# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 189750300b2c82a9a696dcc528debdaf521e594e61b1ea6af1f81f5a5aa697e0304e2d3dcb085e3e8608d05b7d22f9eb800d22e84b047fde3fd0f82e0ab62809

test:
  secret_key_base: a98d432c63ab7f77e087542f6a67cd7919f40ae7d98fbb6e84eb25f655d8315a096e29062b02ec5e9655f63e1310972affec8a9d7f7f03c4639ab937828c1273

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
